import "../app/globals.css"
import LayoutProvider from "./components/layoutProvider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Job Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <LayoutProvider>{children}</LayoutProvider>
  );
}
